# CI job that builds, tests and analyzes the branch / pull request

name: Maven Build

on:
  pull_request:
    paths-ignore: 
      - '.github/**'
      - '!.github/workflows/maven.yml'
      - '.idea/**'
  push:
    paths-ignore: 
      - '.github/**'
      - '!.github/workflows/maven.yml'
      - '.idea/**'
    # disable temporary
#    branches-ignore:
#      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch whole git history
        run: |
          git fetch --prune --unshallow
      - name: Read Git Coordinates - Branch
        id: push-branch-name
        if: github.event_name == 'push'
        uses: actions/github-script@0.9.0
        with:
          # payload schema: https://developer.github.com/v3/activity/events/types/#pushevent
          script: |
            const fullGitRef = context.ref;
            const branchName = fullGitRef.replace(/refs\/\w+\//i,'');
            core.setOutput('PUSH_BRANCH_NAME', branchName);
      - name: Read Git Coordinates - Pull Request
        id: pull-request-name
        if: github.event_name == 'pull_request'
        uses: actions/github-script@0.9.0
        with:
          # payload schema: https://developer.github.com/v3/activity/events/types/#pullrequestevent
          script: |
            core.setOutput('PULL_REQUEST_SOURCE_BRANCH_NAME', context.payload.pull_request.head.ref);
            core.setOutput('PULL_REQUEST_TARGET_BRANCH_NAME', context.payload.pull_request.base.ref);
            core.setOutput('PULL_REQUEST_NUMBER', context.payload.number.toString());
      - name: Build with Maven
        run: |
          mvn --file pom.xml --batch-mode \
            verify -P ci-run
      - name: Sonar Analysis with Maven (sonarcloud.io) - Branch
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: |
          mvn --file pom.xml --batch-mode \
            sonar:sonar \
            -Dsonar.login=$SONARCLOUD_TOKEN \
            -Dsonar.branch.name=${{ steps.push-branch-name.outputs.PUSH_BRANCH_NAME }}
      - name: Sonar Analysis with Maven (sonarcloud.io) - Pull Request
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: |
          mvn --file pom.xml --batch-mode \
            sonar:sonar \
            -Dsonar.login=$SONARCLOUD_TOKEN \
            -Dsonar.pullrequest.branch=${{ steps.pull-request-name.outputs.PULL_REQUEST_SOURCE_BRANCH_NAME }} \
            -Dsonar.pullrequest.base=${{ steps.pull-request-name.outputs.PULL_REQUEST_TARGET_BRANCH_NAME }} \
            -Dsonar.pullrequest.key=${{ steps.pull-request-name.outputs.PULL_REQUEST_NUMBER }}

  run-co-pilot:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload to CoPilot
        run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)
